DROP TABLE IF EXISTS ft_airport;
DROP TABLE IF EXISTS ft_country;
DROP TABLE IF EXISTS ft_review;
DROP TABLE IF EXISTS ft_airline;
DROP TABLE IF EXISTS ft_reservation;
DROP TABLE IF EXISTS ft_flightinfo;